//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanSach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHOADONBAN
    {
        public int MaHD { get; set; }
        public int MaSach { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual HOADONBAN HOADONBAN { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
