//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanSach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEUNHAP
    {
        public int MaPN { get; set; }
        public int MaSach { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<decimal> DonGiaNhap { get; set; }
        public Nullable<decimal> ThanhTienNhap { get; set; }
    
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
